# Ollama Local
OLLAMA_BASE_URL = "http://localhost:11434/v1"
OLLAMA_API_KEY  = "ollama"   # string dummy saja
OLLAMA_MODEL    = "gemma3:4b"

# OpenAI (opsional, kalau mau switch ke OpenAI Cloud)
OPENAI_API_KEY  = ""
OPENAI_MODEL    = "gpt-4o-mini"
